export const Actions = {
    PAGE_LOGIN: 'PAGE_LOGIN',
    PAGE_SIGNUP: 'PAGE_SIGNUP',
    PAGE_CHAT: 'PAGE_CHAT',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SIGNUP: 'SIGNUP',

    CHAT_MESSAGE: 'CHAT_MESSAGE',
    LOAD_MESSAGE: 'LOAD_MESSAGE',

    CREATE_CONVERSATION: 'CREATE_CONVERSATION',
    LOAD_CONVERSATION_LIST: 'LOAD_CONVERSATION_LIST',
    

    CREATE_CHANNEL: 'CREATE_CHANNEL',
    EXIT_CHANNEL: 'EXIT_CHANNEL',
    LOAD_CHANNEL_LIST: 'LOAD_CHANNEL_LIST',

    CHANGE_CURRENT_CHAT: 'CHANGE_CURRENT_CHAT',
};
 
